import 'package:flutter_test/flutter_test.dart';
import 'package:json_to_dart/generator/naming.dart';

void main() {
  group("Naming.className", () {
    test("keeps valid PascalCase", () {
      expect(Naming.className("MyClass"), "MyClass");
    });

    test("converts keys", () {
      expect(Naming.className("user_name"), "UserName");
      expect(Naming.className("url"), "Url");
      expect(Naming.className("address2"), "Address2");
    });

    test("falls back for empty or symbol-only input", () {
      expect(Naming.className(""), "AutoGenerated");
      expect(Naming.className("  "), "AutoGenerated");
      expect(Naming.className("---"), "AutoGenerated");
    });

    test("avoids built-in type names", () {
      expect(Naming.className("list"), "ListModel");
    });

    test("prefixes leading digits", () {
      expect(Naming.className("2fast"), "A2Fast");
    });
  });

  group("Naming.fieldName", () {
    test("converts to camelCase", () {
      expect(Naming.fieldName("user_name"), "userName");
      expect(Naming.fieldName("userID"), "userId");
      expect(Naming.fieldName("URL"), "url");
    });

    test("avoids reserved words", () {
      expect(Naming.fieldName("class"), "classValue");
      expect(Naming.fieldName("default"), "defaultValue");
      expect(Naming.fieldName("toJson"), "toJsonValue");
    });

    test("handles empty and numeric keys", () {
      expect(Naming.fieldName(""), "field");
      expect(Naming.fieldName("1"), "a1");
    });
  });

  group("Naming.singular", () {
    test("singularizes common plurals", () {
      expect(Naming.singular("items"), "item");
      expect(Naming.singular("categories"), "category");
      expect(Naming.singular("boxes"), "box");
      expect(Naming.singular("addresses"), "address");
    });

    test("leaves non-plurals alone", () {
      expect(Naming.singular("status"), "status");
      expect(Naming.singular("class"), "class");
      expect(Naming.singular("data"), "data");
      expect(Naming.singular("s"), "s");
    });
  });

  group("Naming.fileName", () {
    test("converts to snake_case", () {
      expect(Naming.fileName("MyClass"), "my_class");
      expect(Naming.fileName(""), "auto_generated");
      expect(Naming.fileName("MyURLParser"), "my_url_parser");
    });
  });
}
