@TestOn("browser")
library;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:json_to_dart/screens/home.dart';
import 'package:shared_preferences/shared_preferences.dart';

String? _clipboard;

Future<Object?> _platformCalls(MethodCall call) async {
  if (call.method == "Clipboard.setData") {
    _clipboard = (call.arguments as Map<Object?, Object?>)["text"] as String?;
  } else if (call.method == "Clipboard.getData") {
    return {"text": _clipboard};
  }
  return null;
}

Future<void> _pumpApp(WidgetTester tester) async {
  tester.view
    ..physicalSize = const Size(1300, 900)
    ..devicePixelRatio = 1;
  addTearDown(tester.view.reset);
  await tester.pumpWidget(
    MaterialApp(home: HomeScreen(onToggleTheme: (_) {})),
  );
  await tester.pump(const Duration(milliseconds: 100));
}

Future<void> _settle(WidgetTester tester) =>
    tester.pump(const Duration(milliseconds: 500));

String _code(WidgetTester tester) {
  final Iterable<SelectableText> texts =
      tester.widgetList<SelectableText>(find.byType(SelectableText));
  return texts.map((t) => t.data ?? "").join("\n");
}

Finder _jsonField() => find.byType(TextField).at(1);

Future<void> _loadSample(WidgetTester tester) async {
  await tester.tap(find.text("Try a sample"));
  await _settle(tester);
}

Future<void> _tapChip(WidgetTester tester, String label) async {
  await tester.tap(find.widgetWithText(FilterChip, label));
  await _settle(tester);
}

void main() {
  setUp(() {
    _clipboard = null;
    SharedPreferences.setMockInitialValues({});
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(SystemChannels.platform, _platformCalls);
  });

  testWidgets("empty state offers a sample and generates code", (tester) async {
    await _pumpApp(tester);
    expect(find.text("Generated Dart code will appear here."), findsOneWidget);
    await _loadSample(tester);
    expect(_code(tester), contains("class AutoGenerated {"));
    expect(find.textContaining("3 classes"), findsOneWidget);
    expect(find.text("Try a sample"), findsNothing);
  });

  testWidgets("option chips regenerate the output", (tester) async {
    await _pumpApp(tester);
    await _loadSample(tester);
    expect(_code(tester), contains("toJson"));
    await _tapChip(tester, "toJson");
    expect(_code(tester), isNot(contains("toJson")));
    await _tapChip(tester, "toJson");
    await _tapChip(tester, "copyWith");
    expect(_code(tester), contains("copyWith"));
    await _tapChip(tester, "fromJson");
    expect(_code(tester), isNot(contains("fromJson")));
    final FilterChip parseList =
        tester.widget(find.widgetWithText(FilterChip, "parseList"));
    expect(parseList.onSelected, isNull);
  });

  testWidgets("invalid JSON shows the error with its position", (tester) async {
    await _pumpApp(tester);
    await tester.enterText(_jsonField(), '{\n  "a": x\n}');
    await _settle(tester);
    expect(find.textContaining("line 2"), findsOneWidget);
    expect(
      find.text("Fix the JSON error to see the generated code."),
      findsOneWidget,
    );
  });

  testWidgets("rename dialog renames a nested class", (tester) async {
    await _pumpApp(tester);
    await _loadSample(tester);
    await tester.tap(find.byTooltip("Rename classes"));
    await tester.pumpAndSettle();
    expect(find.text("Rename classes"), findsOneWidget);
    await tester.enterText(
      find
          .descendant(
            of: find.byType(AlertDialog),
            matching: find.byType(TextField),
          )
          .first,
      "Home",
    );
    await tester.tap(find.text("Apply"));
    await tester.pumpAndSettle();
    expect(_code(tester), contains("class Home {"));
    expect(_code(tester), isNot(contains("class Address")));
  });

  testWidgets("ctrl+enter copies the output", (tester) async {
    await _pumpApp(tester);
    await _loadSample(tester);
    await tester.sendKeyDownEvent(LogicalKeyboardKey.controlLeft);
    await tester.sendKeyEvent(LogicalKeyboardKey.enter);
    await tester.sendKeyUpEvent(LogicalKeyboardKey.controlLeft);
    await tester.pump();
    expect(_clipboard, startsWith("class AutoGenerated"));
    expect(find.byIcon(Icons.check), findsOneWidget);
    await tester.pump(const Duration(seconds: 3));
    expect(find.byIcon(Icons.check), findsNothing);
  });

  testWidgets("share link copies a URL with the state", (tester) async {
    await _pumpApp(tester);
    await _loadSample(tester);
    await tester.tap(find.byTooltip("Copy share link"));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 300));
    expect(find.text("Share link copied to clipboard"), findsOneWidget);
    expect(_clipboard, contains("?s="));
  });

  testWidgets("recent inputs can be restored", (tester) async {
    await _pumpApp(tester);
    await tester.tap(find.byTooltip("Recent inputs"), warnIfMissed: false);
    await tester.pump();
    expect(find.text("Clear recent inputs"), findsNothing);
    await tester.enterText(_jsonField(), '{"first": 1}');
    await _settle(tester);
    await tester.tap(find.byTooltip("Clear"));
    await _settle(tester);
    expect(_code(tester), isEmpty);
    await tester.tap(find.byTooltip("Recent inputs"));
    await tester.pumpAndSettle();
    await tester.tap(find.textContaining('{"first": 1}'));
    await tester.pumpAndSettle();
    expect(_code(tester), contains("final int first;"));
  });

  testWidgets("large input swaps the editor for a preview", (tester) async {
    await _pumpApp(tester);
    final String big =
        '{"items":[${List.filled(15000, '{"id":1,"n":"abcdefghij"}').join(",")}]}';
    await tester.enterText(_jsonField(), big);
    await _settle(tester);
    expect(find.textContaining("Large input"), findsOneWidget);
    expect(find.byType(TextField), findsOneWidget);
    expect(_code(tester), contains("class Item {"));
    await tester.tap(find.byTooltip("Clear"));
    await _settle(tester);
    expect(find.byType(TextField), findsNWidgets(2));
  });

  testWidgets("state persists across reloads", (tester) async {
    await _pumpApp(tester);
    await tester.enterText(find.byType(TextField).first, "Saved");
    await tester.enterText(_jsonField(), '{"a": 1}');
    await _tapChip(tester, "Mutable fields");
    await tester.pumpWidget(const SizedBox());
    await _pumpApp(tester);
    await _settle(tester);
    expect(_code(tester), contains("class Saved {"));
    expect(_code(tester), contains("  int a;"));
  });

  testWidgets("controls expose accessible names and states", (tester) async {
    final SemanticsHandle handle = tester.ensureSemantics();
    await _pumpApp(tester);
    await _loadSample(tester);
    expect(find.bySemanticsLabel("JSON input"), findsOneWidget);
    expect(find.bySemanticsLabel("Generated Dart code"), findsOneWidget);
    expect(
      find.bySemanticsLabel("Copy class code to clipboard"),
      findsOneWidget,
    );
    expect(find.bySemanticsLabel("Rename generated classes"), findsOneWidget);
    expect(find.bySemanticsLabel("Format JSON"), findsOneWidget);
    expect(
      tester.getSemantics(find.widgetWithText(FilterChip, "toJson")),
      matchesSemantics(
        label: "toJson",
        isButton: true,
        hasCheckedState: true,
        isChecked: true,
        hasEnabledState: true,
        isEnabled: true,
        isFocusable: true,
        hasTapAction: true,
        hasFocusAction: true,
      ),
    );
    expect(
      tester.getSemantics(find.widgetWithText(FilterChip, "copyWith")),
      matchesSemantics(
        label: "copyWith",
        isButton: true,
        hasCheckedState: true,
        hasEnabledState: true,
        isEnabled: true,
        isFocusable: true,
        hasTapAction: true,
        hasFocusAction: true,
      ),
    );
    handle.dispose();
  });
}
