name: json_to_dart
description: "Converts JSON into Dart classes: nested, nullable-aware, with fromJson, toJson and parseList."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  web: ^1.1.1
  shared_preferences: ^2.5.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true