name: json_to_dart
description: "A Flutter web app simplifying the conversion of JSON data into Dart classes effortlessly."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  web: ^1.1.1
  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true