import 'package:flutter/material.dart';
import 'package:json_to_dart/controllers/converter_controller.dart';
import 'package:json_to_dart/generator/generator_options.dart';
import 'package:json_to_dart/widgets/option_chip.dart';

class OptionsBar extends StatelessWidget {
  const OptionsBar({required this.controller, required this.wide, super.key});

  static const double _classFieldWidth = 180;

  final ConverterController controller;
  final bool wide;

  @override
  Widget build(BuildContext context) {
    final Widget classField = TextField(
      controller: controller.classNameController,
      decoration: const InputDecoration(
        labelText: "Class name",
        hintText: "AutoGenerated",
        isDense: true,
        border: OutlineInputBorder(),
      ),
      onChanged: (_) => controller.onInputChanged(),
    );
    return ListenableBuilder(
      listenable: controller,
      builder: (context, _) {
        final Widget chips = _buildChips();
        if (!wide) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [classField, const SizedBox(height: 12), chips],
          );
        }
        return Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(width: _classFieldWidth, child: classField),
            const SizedBox(width: 16),
            Expanded(child: chips),
          ],
        );
      },
    );
  }

  Widget _buildChips() {
    final GeneratorOptions o = controller.options;
    void update(GeneratorOptions options) => controller.setOptions(options);
    return Wrap(
      spacing: 8,
      runSpacing: 8,
      children: [
        OptionChip(
          label: "fromJson",
          selected: o.fromJson,
          onChanged: (v) => update(o.copyWith(fromJson: v)),
        ),
        OptionChip(
          label: "toJson",
          selected: o.toJson,
          onChanged: (v) => update(o.copyWith(toJson: v)),
        ),
        OptionChip(
          label: "parseList",
          selected: o.effectiveParseList,
          onChanged:
              o.fromJson ? (v) => update(o.copyWith(parseList: v)) : null,
        ),
        OptionChip(
          label: "copyWith",
          selected: o.copyWithMethod,
          onChanged: (v) => update(o.copyWith(copyWithMethod: v)),
        ),
        OptionChip(
          label: "== and hashCode",
          selected: o.equality,
          onChanged: (v) => update(o.copyWith(equality: v)),
        ),
        OptionChip(
          label: "Detect dates",
          selected: o.detectDates,
          onChanged: (v) => update(o.copyWith(detectDates: v)),
        ),
        OptionChip(
          label: "Detect maps",
          selected: o.detectMaps,
          onChanged: (v) => update(o.copyWith(detectMaps: v)),
        ),
        OptionChip(
          label: "All nullable",
          selected: o.allNullable,
          onChanged: (v) => update(o.copyWith(allNullable: v)),
        ),
      ],
    );
  }
}
