class Naming {
  static const String defaultClassName = "AutoGenerated";

  static final RegExp _wordPattern =
      RegExp("[A-Z]+(?![a-z])|[A-Z]?[a-z]+|[0-9]+");
  static final RegExp _validClassName = RegExp(r"^[A-Z][A-Za-z0-9]*$");

  static const Set<String> _reservedWords = {
    "assert", "break", "case", "catch", "class", "const", "continue",
    "default", "do", "else", "enum", "extends", "false", "final", "finally",
    "for", "if", "in", "is", "new", "null", "rethrow", "return", "super",
    "switch", "this", "throw", "true", "try", "var", "void", "while", "with",
    "hashCode", "runtimeType", "toString", "toJson", "noSuchMethod",
  };

  static const Set<String> _builtInTypes = {
    "String", "List", "Map", "Set", "Object", "Type", "Function", "DateTime",
    "Null", "Iterable", "Record", "Never", "Enum", "Future", "Stream",
  };

  static List<String> _words(String input) =>
      _wordPattern.allMatches(input).map((m) => m.group(0)!).toList();

  static String _capitalize(String word) =>
      "${word[0].toUpperCase()}${word.substring(1).toLowerCase()}";

  static String _pascalCase(String input) {
    final String joined = _words(input).map(_capitalize).join();
    if (joined.isEmpty) return joined;
    return RegExp("^[0-9]").hasMatch(joined) ? "A$joined" : joined;
  }

  static String className(String input) {
    final String trimmed = input.trim();
    final String name =
        _validClassName.hasMatch(trimmed) ? trimmed : _pascalCase(trimmed);
    if (name.isEmpty) return defaultClassName;
    return _builtInTypes.contains(name) ? "${name}Model" : name;
  }

  static String fieldName(String input) {
    final String pascal = _pascalCase(input);
    if (pascal.isEmpty) return "field";
    final String name = "${pascal[0].toLowerCase()}${pascal.substring(1)}";
    return _reservedWords.contains(name) ? "${name}Value" : name;
  }

  static String fileName(String input) {
    final List<String> words = _words(className(input));
    return words.map((w) => w.toLowerCase()).join("_");
  }
}
